#lidar_topic: /hesai/pandar
lidar_topic: /rslidar_points
imu_topic: /imu/data
lidar_type: Hesai # livox velodyne ouster Hesai Bpearl
min_radius: 1
max_radius: 100
point_filter_num: 5
# time_scale: 0 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.01
ba_cov: 0.0001
bg_cov: 0.0001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001


# botanic graden

#t_imu_lidar : [-0.011775 -0.006253 -0.0438256454]
#R_imu_lidar: [1, 0, 0,
#              0, -1, 0,
#              0, 0, -1]

t_imu_lidar : [0.16592 0.06659 0.13617]
R_imu_lidar: [0.9526330, 0, 0.3041224,
              0, 1, 0,
              -0.3041224, 0, 0.9526330]
              
